### ISSUE TITLE
Whirlpool

### ISSUE THREAD

**Issue by donavanbecker** [funkybunch/NodeTag#1]
I am guessing this should also support whirlpool? 

Any chance of adding smart oven support?

Any plans to publish to npm?

**Comment by funkybunch** [comment]
No testing has been done with whirlpool products.  There are no plans to publish via npm or add oven support.  If you want to add support and submit a PR you're welcome to.

If you test it on Whirlpool products and it does work, feel free to submit a PR to update the README.
