### ISSUE TITLE
Maytag Washer

### ISSUE THREAD

**Issue by bnieves1994** [funkybunch/NodeTag#2]
My node is not refreshing the token every 21599 seconds is this supposed to happen?

![image](https://user-images.githubusercontent.com/89528841/179234910-4974039e-296e-43b4-9d9d-874703e179bd.png)

**Comment by funkybunch** [comment]
Are you going off of the log messages?  Or are you getting auth errors after 6 hours?  That is a standard message to tell you the authentication method anytime where was a successful authentication.  After 6 hours there should be a similar one that says authenticated via refresh token.

Please include error logs if there really is an issue.  The logs above don't indicate anything out of the ordinary.

**Comment by funkybunch** [comment]
Closing as stale & archiving the project in favor of getting this working with the existing HA integration.
